/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

public class TelaFilmes extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaFilmes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGodzila = new javax.swing.JButton();
        BtnShirley = new javax.swing.JButton();
        BtnMergulhoProfundo = new javax.swing.JButton();
        BtnMinhaIrmaEEu = new javax.swing.JButton();
        BtnJogosDeAmor = new javax.swing.JButton();
        BtnDuna2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnGodzila.setContentAreaFilled(false);
        BtnGodzila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGodzila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGodzilaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGodzila, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 110, 40));

        BtnShirley.setContentAreaFilled(false);
        BtnShirley.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnShirley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShirleyActionPerformed(evt);
            }
        });
        getContentPane().add(BtnShirley, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 110, 30));

        BtnMergulhoProfundo.setContentAreaFilled(false);
        BtnMergulhoProfundo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMergulhoProfundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMergulhoProfundoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMergulhoProfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 110, 30));

        BtnMinhaIrmaEEu.setContentAreaFilled(false);
        BtnMinhaIrmaEEu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMinhaIrmaEEu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinhaIrmaEEuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMinhaIrmaEEu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 110, 30));

        BtnJogosDeAmor.setContentAreaFilled(false);
        BtnJogosDeAmor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnJogosDeAmor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJogosDeAmorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnJogosDeAmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 110, 40));

        BtnDuna2.setContentAreaFilled(false);
        BtnDuna2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDuna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDuna2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDuna2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/telaFilmes.png"))); // NOI18N
        jLabel1.setText("jLabel2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -90, 790, 550));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/telaFilmes.png")));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGodzilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGodzilaActionPerformed
        
    }//GEN-LAST:event_BtnGodzilaActionPerformed

    private void BtnShirleyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShirleyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnShirleyActionPerformed

    private void BtnMergulhoProfundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMergulhoProfundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMergulhoProfundoActionPerformed

    private void BtnMinhaIrmaEEuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinhaIrmaEEuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMinhaIrmaEEuActionPerformed

    private void BtnJogosDeAmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJogosDeAmorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnJogosDeAmorActionPerformed

    private void BtnDuna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDuna2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDuna2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDuna2;
    private javax.swing.JButton BtnGodzila;
    private javax.swing.JButton BtnJogosDeAmor;
    private javax.swing.JButton BtnMergulhoProfundo;
    private javax.swing.JButton BtnMinhaIrmaEEu;
    private javax.swing.JButton BtnShirley;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
